/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chris
 */
public class PassportGUI extends javax.swing.JFrame {
	
	private ActionListener controller;

    /**
     * Creates new form PassportGUI
     */
    public PassportGUI(ActionListener actionListener) {
    	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.controller = actionListener;
        initComponents();
        hideInvalidLoginLabel();
        hideInvalidPasswordLabel();
        setTitle("Covid-19 Data");
    }

    public void addHotspotRow(String place, long curCases, long totalCases, long totalDeaths, long totalRecovered,long totalVaccinations){

        Object[] row = {place,curCases,totalCases,totalDeaths,totalRecovered,totalVaccinations};

        DefaultTableModel model = (DefaultTableModel) hotspotTable.getModel();

        model.addRow(row);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginDialog = new javax.swing.JDialog();
        titleLabel = new javax.swing.JLabel();
        optionButtons = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        accountLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwdLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        invalidLoginLabel = new javax.swing.JLabel();
        invalidPasswordLabel = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        InfectionLabel = new javax.swing.JLabel();
        DeathLabel = new javax.swing.JLabel();
        RecoveredLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalRecoveredOutput = new javax.swing.JLabel();
        totalInfectedOutput = new javax.swing.JLabel();
        totalDeathsOutput = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        vaccineTitleLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        vaccinatedLabel = new javax.swing.JLabel();
        vaccinatedOutput = new javax.swing.JLabel();
        vaccineDateLabel = new javax.swing.JLabel();
        vaccineDateOutput = new javax.swing.JLabel();
        dosesLabel = new javax.swing.JLabel();
        dosesOutput = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hotspotTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        loginDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginDialog.setTitle("Login");
        loginDialog.setBounds(new java.awt.Rectangle(0, 25, 350, 225));
        loginDialog.setModal(true);
        loginDialog.setResizable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Login to view Vacination Information");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginDialog.getContentPane().add(titleLabel, java.awt.BorderLayout.NORTH);

        loginBtn.setText("Login");
        loginBtn.addActionListener(controller);
        optionButtons.add(loginBtn);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        optionButtons.add(cancelBtn);

        loginDialog.getContentPane().add(optionButtons, java.awt.BorderLayout.SOUTH);

        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {100, 200};
        jPanel4.setLayout(jPanel4Layout);

        accountLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        accountLabel.setText("NHS Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(accountLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(loginField, gridBagConstraints);

        passwdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwdLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(passwdLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(passwordField, gridBagConstraints);

        invalidLoginLabel.setForeground(new java.awt.Color(255, 51, 0));
        invalidLoginLabel.setText("* invalid NHS number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanel4.add(invalidLoginLabel, gridBagConstraints);

        invalidPasswordLabel.setForeground(new java.awt.Color(255, 51, 0));
        invalidPasswordLabel.setText("* password invalid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanel4.add(invalidPasswordLabel, gridBagConstraints);

        loginDialog.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TabbedPane.setBackground(java.awt.Color.white);
        TabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setBackground(java.awt.Color.white);

        InfectionLabel.setText("Total Infections");

        DeathLabel.setText("Total Deaths");

        RecoveredLabel.setText("Total Recovered");

        jLabel8.setText("National Statistics");

        totalRecoveredOutput.setText(":                    ");

        totalInfectedOutput.setText(":                    ");

        totalDeathsOutput.setText(":                    ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(RecoveredLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRecoveredOutput)
                .addGap(88, 88, 88)
                .addComponent(InfectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalInfectedOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(DeathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalDeathsOutput)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfectionLabel)
                    .addComponent(DeathLabel)
                    .addComponent(RecoveredLabel)
                    .addComponent(totalRecoveredOutput)
                    .addComponent(totalInfectedOutput)
                    .addComponent(totalDeathsOutput))
                .addGap(0, 174, Short.MAX_VALUE))
        );

        totalRecoveredOutput.getAccessibleContext().setAccessibleName("TotalRecovered_Number");

        TabbedPane.addTab("National Statistics", jPanel1);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        vaccineTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vaccineTitleLabel.setText("Vaccination Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 50, 50);
        jPanel3.add(vaccineTitleLabel, gridBagConstraints);

        LoginButton.setBackground(java.awt.Color.cyan);
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 10, 10);
        jPanel3.add(LoginButton, gridBagConstraints);

        vaccinatedLabel.setText("Vaccinated:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(vaccinatedLabel, gridBagConstraints);

        vaccinatedOutput.setText("---");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel3.add(vaccinatedOutput, gridBagConstraints);

        vaccineDateLabel.setText("Date of most recent vaccination:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(vaccineDateLabel, gridBagConstraints);

        vaccineDateOutput.setText("---");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel3.add(vaccineDateOutput, gridBagConstraints);

        dosesLabel.setText("Doses taken:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(dosesLabel, gridBagConstraints);

        dosesOutput.setText("---");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel3.add(dosesOutput, gridBagConstraints);

        TabbedPane.addTab("Vaccination Status", jPanel3);

        hotspotTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hotspotTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place", "Current Cases", "Total Cases", "Total Deaths", "Total Recovered", "Density", "Total Vaccinations"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(hotspotTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Hotspot Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        TabbedPane.addTab("Hotspot Information", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        loginDialog.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        loginDialog.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    public void setNationalStatisticsLabels(long totalInfected, long totalDeaths) {
    	totalInfectedOutput.setText(String.valueOf(totalInfected));
    	totalDeathsOutput.setText(String.valueOf(totalDeaths));
    	totalRecoveredOutput.setText(String.valueOf(totalInfected - totalDeaths));
    }
    
    public String getEnteredLoginNumber() {
        return loginField.getText();
    }
    
    public String getEnteredLoginPassword() {
        return passwordField.getText();
    }
    
    public void hideInvalidLoginLabel() {
        invalidLoginLabel.setVisible(false);
    }
    
    public void hideInvalidPasswordLabel() {
        invalidPasswordLabel.setVisible(false);
    }
    
    public void displayInvalidLoginLabel() {
        invalidLoginLabel.setVisible(true);
    }
     
    public void displayInvalidPasswordLabel() {
        invalidPasswordLabel.setVisible(true);
    }
    
    public void closeLoginDialog() {
        loginDialog.dispose();
    }
    
    public void showVaccinated(boolean vaccinated) {
        if(vaccinated) {
            vaccinatedOutput.setText("Yes");
        } else {
            vaccinatedOutput.setText("No");
        }
    }
    
    public void showVaccineDate(String date) {
        vaccineDateOutput.setText(date);
    }
    
    public void showDoses(int doses) {
        dosesOutput.setText(String.valueOf(doses));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeathLabel;
    private javax.swing.JLabel InfectionLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel RecoveredLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel dosesLabel;
    private javax.swing.JLabel dosesOutput;
    private javax.swing.JTable hotspotTable;
    private javax.swing.JLabel invalidLoginLabel;
    private javax.swing.JLabel invalidPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JTextField loginField;
    private javax.swing.JPanel optionButtons;
    private javax.swing.JLabel passwdLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalDeathsOutput;
    private javax.swing.JLabel totalInfectedOutput;
    private javax.swing.JLabel totalRecoveredOutput;
    private javax.swing.JLabel vaccinatedLabel;
    private javax.swing.JLabel vaccinatedOutput;
    private javax.swing.JLabel vaccineDateLabel;
    private javax.swing.JLabel vaccineDateOutput;
    private javax.swing.JLabel vaccineTitleLabel;
    // End of variables declaration//GEN-END:variables
}
